name: CI

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
  pull_request:

jobs:
  windows-build-and-verify:
    name: Build & verify (windows-latest)
    uses: ./.github/workflows/_windows-native-build.yml
    with:
      native-build-type: Release
      run-verify-samples: true
      run-native-smoke-test: true
      run-publish-to-maven-local: true
      upload-artifacts: true
      artifact-prefix: ci-windows-native
